# Tentando renderizar um cubo

O cubo possui normais

## Importações

In [1]:
import sys
import os

import numpy as np
from tqdm import tqdm

sys.path.append(os.path.abspath(os.path.join('../../..')))

from Atividade02.src.vectorized.Vec3 import Point3

from Atividade03.src.Model import Model

from Atividade04.src.classes.Triangle import Triangle
from Atividade04.src.classes.Sphere import Sphere
from Atividade04.src.classes.HittableList import HittableList
from Atividade04.src.classes.Camera import Camera

## Renderizando o cubo

In [2]:
camera = Camera(image_width=200, samples_per_pixel=10, max_depth=10)

world = HittableList()
model = Model('../../../Atividade03/objs/Cube.obj')
for face in model.faces:
    world.add(face)
    print(face.normals)
world.add(Sphere(Point3([0, -100.5, -1]), 100))

camera.render(world, "../../imgs/cube-simple.png")

[0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 0.0 -1.0]
[0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 0.0 -1.0]
[-1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 0.0]
[-1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0 0.0]
[0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0]
[0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0]
[1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0]
[1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0]
[0.0 -1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0]
[0.0 -1.0 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0]
[0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0]
[0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0]


  0%|          | 0/112 [00:00<?, ?it/s]

 55%|█████▌    | 62/112 [01:35<01:17,  1.54s/it]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()