# Testes da classe ImageOutput

## Importações

In [2]:
from ImageOutput import ImageOutput
import numpy as np

## Salvando e visualizando imagem degradê

In [15]:
img_width = 256
img_height = 1000

top_color = np.array([0, 0, 255])
bottom_color = np.array([255, 0, 0])

img_matrix = np.zeros((img_height, img_width, 3), dtype=np.uint8)

for i in range(img_height):
    img_matrix[i] += (bottom_color * (i / img_height)).astype(np.uint8)
    img_matrix[i] += (top_color * (1 - i / img_height)).astype(np.uint8)

print(img_matrix)
img_output = ImageOutput(img_matrix)

img_output.display()

[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 254]
  [  0   0 254]
  [  0   0 254]
  ...
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]]

 [[  0   0 254]
  [  0   0 254]
  [  0   0 254]
  ...
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]]

 ...

 [[254   0   0]
  [254   0   0]
  [254   0   0]
  ...
  [254   0   0]
  [254   0   0]
  [254   0   0]]

 [[254   0   0]
  [254   0   0]
  [254   0   0]
  ...
  [254   0   0]
  [254   0   0]
  [254   0   0]]

 [[254   0   0]
  [254   0   0]
  [254   0   0]
  ...
  [254   0   0]
  [254   0   0]
  [254   0   0]]]


## Salvando e visualizando imagem circulo

## Salvando e visualizando imagem de quadrado